name: 🐛 Bug Report
description: Report something that isn’t working as expected
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Help us squash bugs! Provide as much context and detail as possible.
  - type: input
    id: title
    attributes:
      label: Bug Title
      placeholder: e.g. Driver map not updating
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What Happened?
      description: Clearly describe the bug, steps to reproduce, and expected vs actual behavior.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Browser, OS, device, and app version — anything that helps reproduce it.
  - type: dropdown
    id: scope
    attributes:
      label: Affected Area
      description: Which part of the app is this bug in?
      options:
        - client-app
        - driver-app
        - shared
        - functions
        - root
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **🐞 Suggested Branch Naming Convention**
        
        To fix this bug, create a branch named:
        
        ```
        fix/<scope>-<slugified-title>
        ```

        Example: `fix/driver-map-update-issue`

        Use short, dash-separated keywords. For refactors instead of bugs, use `refactor/` instead.
